name: Auto Format with Ruff

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  format:
    permissions:
      contents: write
    uses: EECE5644/workflows/.github/workflows/ruff-format.yaml@main
